name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  unit:
    name: Test ${{ matrix.java }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        java: [ '1.8', '1.11' ]
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: ${{ matrix.java }}
      - name: Run unit tests
        run: sbt +test
        shell: bash
  checks:
    name: Run Scalafmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v7
      - name: Run Scalafmt
        run: sbt scalafmtCheckAll
